export const constants = {
  SALT_PASSWORD: 12,

  EMAIL_TOKEN_EXP_IN_PLAIN_TEXT: '30 minutos',

  APPLICATION_NAME: 'ShopixTurbo',

  MAIL_QUEUE: 'mail',
  SEND_VERIFICATION_EMAIL_JOB: 'send-verification-email',

  PRODUCTS_SYNC_QUEUE: 'products-sync',
  PRODUCTS_SYNC_JOB: 'products-sync-job',

  ONE_HOUR_IN_SECONDS: 3600,
  FIVE_MINUTES_IN_MILLISECONDS: 5 * 60 * 1000,

  PAGE_SIZE_PRODUCTS_SYNC: 100,
  MAX_NUMBER_PRODUCTS_ALLOWED_FOR_QUERY: 100,
  MAX_PRODUCTS_PAGE: 500,

  MAX_TIME_INTERVAL_ORDERS: 15,
  DAY_IN_SECONDS: 60 * 60 * 24,

  MAX_NUMBER_PRODUCTS_TO_UPDATE: 100,
};

export type Constants = typeof constants;
